name: trashsmart
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  google_maps_flutter: ^2.12.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.0
  uuid: ^4.5.1
  sqflite: ^2.4.2
  mobile_scanner: ^6.0.10
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  freezed_annotation: ^3.0.0
  flutter_svg: ^2.1.0
  flutter_spinkit: ^5.2.1
  dartz: ^0.10.1  
  geolocator: ^14.0.0
  youtube_player_iframe: ^5.2.1
  http: ^1.3.0
  equatable: ^2.0.7
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  google_sign_in: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.10.0
  freezed: ^3.0.6
  flutter_gen: ^5.10.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/app_icon.png" 
  min_sdk_android: 23
  
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/maps.png
    - assets/icons/
    - assets/kategori/
